sudo: required
services:
  - docker

before_install:
  - docker build -t sjmcdowall/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sjmcdowall/react-test npm test

after_success:
  - docker build -t sjmcdowall/multi-client ./client
  - docker build -t sjmcdowall/multi-nginx ./nginx
  - docker build -t sjmcdowall/multi-server ./server
  - docker build -t sjmcdowall/multi-worker ./worker

  # Push to docker hub
  # Step 1) Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Step 2 now we can do the pushes
  - docker push sjmcdowall/multi-client
  - docker push sjmcdowall/multi-nginx
  - docker push sjmcdowall/multi-server
  - docker push sjmcdowall/multi-worker

# Now deploy to AWS EBS
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-465201686747'
  bucket_path: 'multi-docker'
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master
